# Generated by Django 3.1.4 on 2021-08-28 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('background_image', models.ImageField(blank=True, null=True,
                                                       upload_to='hero/backgrounds/', verbose_name='background image')),
                ('foreground_image', models.ImageField(blank=True, null=True,
                                                       upload_to='hero/foregrounds/', verbose_name='foreground image')),
                ('text', models.CharField(blank=True,
                                          max_length=255, null=True, verbose_name='text')),
                ('position', models.PositiveIntegerField(
                    default=0, help_text='The order in which to display the hero.', verbose_name='position')),
                ('start', models.DateTimeField(db_index=True, verbose_name='start')),
                ('end', models.DateTimeField(db_index=True,
                                             help_text='The end time must be later than the start time.', verbose_name='end')),
            ],
        ),
        migrations.CreateModel(
            name='HeroCallToAction',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(
                    default=0, help_text='The order in which to display the call to action.', verbose_name='position')),
                ('action_type', models.PositiveIntegerField(choices=[
                 (0, 'Anchor'), (1, 'Button')], default=0, verbose_name='action type')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('link', models.CharField(blank=True,
                                          max_length=255, null=True, verbose_name='link')),
                ('target', models.PositiveBigIntegerField(choices=[
                 (0, '_self'), (1, '_blank'), (2, '_parent'), (3, '_top')], default=0, verbose_name='target')),
                ('hero', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='fragment_hero.hero')),
            ],
        ),
    ]
