# Generated by Django 3.1.4 on 2021-08-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragment_hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='end',
            field=models.DateTimeField(
                blank=True, help_text='The end time must be later than the start time.', null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='start',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='start'),
        ),
    ]
